// import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Authentic Phones",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased overflow-x-hidden scroll-smooth`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
